// Code generated by "stringer -type=ActionType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Insert-0]
	_ = x[Delete-1]
	_ = x[Update-2]
}

const _ActionType_name = "InsertDeleteUpdate"

var _ActionType_index = [...]uint8{0, 6, 12, 18}

func (i ActionType) String() string {
	if i < 0 || i >= ActionType(len(_ActionType_index)-1) {
		return "ActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionType_name[_ActionType_index[i]:_ActionType_index[i+1]]
}
